### ISSUE TITLE
Empty Match Query raises Exception

### ISSUE THREAD

**Issue by n4p4** [FoolCode/SphinxQL-Query-Builder#108]
**query:**
`$this->sphinxql->create($conn)->select()->from('users')->match('')->compile()->getCompiled()`

**outputs:**
`SELECT * FROM users WHERE MATCH('()')`

which obviously raises an exception in Sphinx.

**It should actually be:**
`SELECT * FROM users WHERE MATCH('')`

what can I do to solve this? Is there a way to get rid of the '()' without modifying the source code?

**Comment by oohnoitz** [comment]
@n4p4 did that resolve your problem?

**Comment by n4p4** [comment]
yes. thanks
