### ISSUE TITLE
[] operator not supported for strings error

### ISSUE THREAD

**Issue by SvetlinStaev** [FoolCode/SphinxQL-Query-Builder#116]
I am trying to update an entity and upon its update to update the information for the entity in the SphinxSearch index. After upgrading to PHP 7.1 I started getting the following error:

`[] operator not supported for strings {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): [] operator not supported for strings at /Users/Svetlin/Projects/symfony/vendor/foolz/sphinxql-query-builder/src/SphinxQL.php:691)"}`

Any idea what might be causing it?

**Comment by woxxy** [comment]
Issue in this library. At https://github.com/FoolCode/SphinxQL-Query-Builder/blob/1.1.0/src/SphinxQL.php#L686-L695 there `$query_sub` should be initialised as an empty array.

Basically `$query_sub = '';` must become `$query_sub = array();`.

See if it works for you.

**Comment by SvetlinStaev** [comment]
Yeah, it does. Thanks!

**Comment by woxxy** [comment]
This is already fixed on branch master https://github.com/FoolCode/SphinxQL-Query-Builder/commit/d288eb84f2b86c4a220fe813cfc14df5f202dfa9 so will leave it at that. Will be fixed in the next tag release which ought to have 7.1 compatibility.

**Comment by oohnoitz** [comment]
According to our tests, it should be compatible. Made a new tag release for it https://github.com/FoolCode/SphinxQL-Query-Builder/tree/1.1.1.

@SvetlinStaev you can point it to that specific version instead of `dev-master` if needed.

**Comment by SvetlinStaev** [comment]
Thanks for the fix!
