### ISSUE TITLE
Where clause automatically changing a dynamic numeric value to  a string type

### ISSUE THREAD

**Issue by joydipnath** [FoolCode/SphinxQL-Query-Builder#119]
Query:
$query = SphinxQL::create($conn)->select('*') ->from('jobs')->where('work_experience_min', '<=', $experience);

Error:
[1064] sphinxql: syntax error, unexpected QUOTED_STRING, expecting CONST_INT or CONST_FLOAT or DOT_NUMBER or '-' near ''3' AND work_experience_min <= '3'' [ SELECT * FROM jobs WHERE work_experience_min <= '3']

**Comment by oohnoitz** [comment]
This seems like the same issue as #89. Could you verify that `$experience` really is coming in as an integer?

**Comment by joydipnath** [comment]
Yes, the above problem has been fixed.
But I wanted to ask, whats the 

> orWhere

 equivalent ?

**Comment by oohnoitz** [comment]
There isn't one since Sphinx [doesn't support](http://sphinxsearch.com/docs/current.html#sphinxql-select) the `OR` operator.

> OR is not supported yet but will be in the future.
