### ISSUE TITLE
support group n by

### ISSUE THREAD

**Issue by hanihh** [FoolCode/SphinxQL-Query-Builder#120]
Hi, 
Thanks for the great library,
However, 
in order to let `WITHIN GROUP ORDER BY` works perfectly
the group by statement needs to be written as `GROUP 20 BY` not only`GROUP BY`
`SELECT
    select_expr [, select_expr ...]
    FROM index [, index2 ...]
    [WHERE where_condition]
    [GROUP [N] BY {col_name | expr_alias} [, {col_name | expr_alias}]]
    [WITHIN GROUP ORDER BY {col_name | expr_alias} {ASC | DESC}]
    [HAVING having_condition]
    [ORDER BY {col_name | expr_alias} {ASC | DESC} [, ...]]
    [LIMIT [offset,] row_count]
    [OPTION opt_name = opt_value [, ...]]
    [FACET facet_options[ FACET facet_options][ ...]]
`
from the documentation:

> Starting with 2.0.1-beta, GROUP BY on a string attribute is supported, with respect for current collation (see the section called “Collations”).
> 
> Starting with 2.2.1-beta, you can query Sphinx to return (no more than) N top matches for each group accordingly to WITHIN GROUP ORDER BY.
> 
> SELECT id FROM products GROUP 3 BY category

I hope this feature can be supported by the library soon as the the function is withinGroupOrderBy() is useless (ordering groups with only one item) :(

Thanks in advance
Regards.

**Comment by oohnoitz** [comment]
This landed in dc9f7f6e5ddb3fbbc5a784ebd145ac5077fc4031.
