### ISSUE TITLE
MAYBE Multimatching

### ISSUE THREAD

**Issue by kono88** [FoolCode/SphinxQL-Query-Builder#122]
Hi

How i can build a query that looks like this ?

`SELECT * FROM my_index WHERE MATCH('@name jurassic MAYBE @description dinosor')`

Ty

**Comment by oohnoitz** [comment]
The following snippet should work:
```
->field('name')
->match('jurrassic')
->maybe()
->field('description')
->match('dinosaur')
```

See https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/tests/SphinxQL/MatchTest.php#L60-L71.

**Comment by kono88** [comment]
I have this error :
Call to undefined method Foolz\\SphinxQL\\SphinxQL::field()

**Comment by oohnoitz** [comment]
It needs to be done on a `Match` instance which is then passed in as a query. So something like this: 
```
$matchQuery = Match::create($sphinxql)
    ->field('name')
    ->match('jurrassic')
    ->maybe()
    ->field('description')
    ->match('dinosaur');

Sphinx::create($conn)->match($matchQuery);
```

You'll need to adjust the code accordingly.
