### ISSUE TITLE
All calls to execute are returning Result object rather than results array?

### ISSUE THREAD

**Issue by kmeekva** [FoolCode/SphinxQL-Query-Builder#126]
I had queries working using Sphinx Querybuilder and when I called the execute function it was returning an array of results as expected.  But suddenly whenever I call any execute I am getting a result object rather than the real results?

The result object says num_rows found -- but doesn't give me the ids?

If use SPHINXQL directly with mysql client from command line  it returns results - so the query it is building is good, but it is not running when execute is called.

I did notice it says  [stat] => ▒#08S01unknown command (code=9) in the result object.  But I can't figure out what is causing this.

Here is program and output when run and the mysql output.
=================================
root@e578707b156b:/www/coder.tns# cat t.php
<?php

require "vendor/autoload.php";

use Foolz\SphinxQL\Connection;
use Foolz\SphinxQL\SphinxQL;

$conn = new Connection();

$conn->setParams(array('host' => 'sphinx', 'port' => 9306));
#print_r(SphinxQL::create($conn)->query('desc ctr_idx')->execute());
#print_r(SphinxQL::create($conn)->query('SHOW TABLES')->execute());

$stime = mktime(0,0,0,10,1,2008);
$etime = mktime(0,0,0,11,1,2008) + (60*60*24);

$sq = SphinxQL::create($conn)->select('id')
    ->from('ctr_idx')
    ->limit(8)
    ->where('content_date', 'BETWEEN', array($stime, $etime))
    ->where('recip_state', 6)
;

$result = $sq->execute();

print_r($result);
print "COMPILED QUERY: " .  $sq->getCompiled();

?>

root@e578707b156b:/www/coder.tns# php t.php
Foolz\SphinxQL\Drivers\Mysqli\ResultSet Object
(
    [connection:protected] => Foolz\SphinxQL\Connection Object
        (
            [internal_encoding:protected] => UTF-8
            [connection_params:protected] => Array
                (
                    [host] => sphinx
                    [port] => 9306
                    [socket] =>
                )

            [connection:protected] => mysqli Object
                (
                    [affected_rows] => 8
                    [client_info] => mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
                    [client_version] => 50012
                    [connect_errno] => 0
                    [connect_error] =>
                    [errno] => 0
                    [error] =>
                    [error_list] => Array
                        (
                        )

                    [field_count] => 1
                    [host_info] => sphinx via TCP/IP
                    [info] =>
                    [insert_id] => 0
                    [server_info] => 2.2.11-id64-release (95ae9a6)
                    [server_version] => 20211
                    [stat] => ▒#08S01unknown command (code=9)
                    [sqlstate] => 00000
                    [protocol_version] => 10
                    [thread_id] => 1
                    [warning_count] => 0
                )

            [silence_connection_warning:protected] =>
        )

    [result:protected] => mysqli_result Object
        (
            [current_field] => 0
            [field_count] => 1
            [lengths] =>
            [num_rows] => 8
            [type] => 0
        )

    [num_rows:protected] => 8
    [cursor:protected] => 0
    [next_cursor:protected] => 0
    [affected_rows:protected] => 0
    [fields:protected] => Array
        (
            [0] => stdClass Object
                (
                    [name] => id
                    [orgname] => id
                    [table] =>
                    [orgtable] =>
                    [def] =>
                    [db] =>
                    [catalog] => def
                    [max_length] => 6
                    [length] => 20
                    [charsetnr] => 33
                    [flags] => 32768
                    [type] => 8
                    [decimals] => 0
                )

        )

    [stored:protected] =>
    [fetched:protected] =>
    [adapter:protected] => Foolz\SphinxQL\Drivers\Mysqli\ResultSetAdapter Object
        (
            [connection:protected] => Foolz\SphinxQL\Connection Object
                (
                    [internal_encoding:protected] => UTF-8
                    [connection_params:protected] => Array
                        (
                            [host] => sphinx
                            [port] => 9306
                            [socket] =>
                        )

                    [connection:protected] => mysqli Object
                        (
                            [affected_rows] => -1
                            [client_info] => mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
                            [client_version] => 50012
                            [connect_errno] => 0
                            [connect_error] =>
                            [errno] => 0
                            [error] =>
                            [error_list] => Array
                                (
                                )

                            [field_count] => 1
                            [host_info] => sphinx via TCP/IP
                            [info] =>
                            [insert_id] => 0
                            [server_info] => 2.2.11-id64-release (95ae9a6)
                            [server_version] => 20211
                            [stat] => ▒#08S01unknown command (code=9)
                            [sqlstate] => 00000
                            [protocol_version] => 10
                            [thread_id] => 1
                            [warning_count] => 0
                        )

                    [silence_connection_warning:protected] =>
                )

            [result:protected] => mysqli_result Object
                (
                    [current_field] => 0
                    [field_count] => 1
                    [lengths] =>
                    [num_rows] => 8
                    [type] => 0
                )

            [valid:protected] => 1
        )

)
COMPILED QUERY: SELECT id FROM ctr_idx WHERE content_date BETWEEN 1222833600 AND 1225598400 AND recip_state = 6 LIMIT 0, 8

root@e578707b156b:/www/coder.tns# mysql  -uroot  -P9306 -hsphinx
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 2.2.11-id64-release (95ae9a6)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT id FROM ctr_idx WHERE content_date BETWEEN 1222833600 AND 1225598400 AND recip_state = 6 LIMIT 0, 8;
+--------+
| id     |
+--------+
| 128242 |
| 128273 |
| 128461 |
| 128480 |
| 128522 |
| 128543 |
| 128564 |
| 128714 |
+--------+
8 rows in set (0.01 sec)

**Comment by kmeekva** [comment]
Thank you so much!!!

This package is great – I must’ve had earlier version and upgraded and suddenly things stopped working..  That will teach me not to reach changelogs..

Kevin

**Comment by oohnoitz** [comment]
I should have done a major version bump instead of a minor version bump with the recent release that contained some of the rework @ergnuor had. That's a mistake on my end.

**Comment by acekid** [comment]
I am so very lost.  I cannot find any documentation for the fetch* methods.  All docs say execute(), and also say that an array is returned.  I see the fetch* methods in the code but I cannot run as I always get a Fatal error: Call to undefined method Foolz\SphinxQL\SphinxQL::fetchAssoc()   Note that everything else works, I can make a direct mysqli connection, I can use sphinxql::execute() and get the object that now no longer has any actual results in it.  I can run queries from the command line.  I just cannot seem to get any meaning full results as I cannot use any of the fetch methods.  What am I missing?

**Comment by kmeekva** [comment]
See my code below that I use to fetch the IDs.  I had to loop thru the results to grab the IDs I wanted.

I never had much luck getting the Try / catch to actually work and show me the error when there was error with my query -- it would just not return results.

I found the $sq->getCompiled(); to be useful to get the actual SPHINX SQL statement generated so I could test it from the mysql command line client to get errors thrown.

Kevin


```
<?php

require "vendor/autoload.php";
use Foolz\SphinxQL\Connection;
use Foolz\SphinxQL\SphinxQL;

$conn = new Connection();
$conn->setParams(array('host' => 'sphinx', 'port' => 9306));

$stime = mktime(0,0,0,10,1,2017);
$etime = mktime(0,0,0,11,1,2017) + (60*60*24);


$sq = SphinxQL::create($conn)->select('id')
    ->from('pr_idx')
     ->match('', SphinxQL::expr('+"Canon City" +Colorado'))
    ->limit(1000)
    ->where(content_date, 'BETWEEN', array($stime, $etime))
;


$result = $sq->execute();

$res = $result->fetchAllAssoc();

print_r($res);

$db_msg .=  "\n" . $sq->getCompiled();
#$res = $sq->query();
}

catch (\Foolz\SphinxQL\DatabaseException $e)
{
        error_log("Error running query ");
        print "Errror";
        print_r($e);
}


if ( is_array($res) ) {
$pr_ids = array();
foreach ( $res as $id ) {
        #print "<br> " . $id['id'];
        $pr_ids[] = $id['id'];
}

```

**Comment by acekid** [comment]
Nevermind, I figured it out:

$conn = new Connection();
$conn->setParams(array('host' => 'localhost', 'port' => 9306));
 
$query = SphinxQL::create($conn)
->select('*')
->from('search')
->match('data', 'shelf');


$result = $query->execute();
$results = $result->fetchAllAssoc();
print_r($results);

Thanks and sorry for being impatient.  I love having my query-builder back!

**Comment by 2ge** [comment]
I run exactly into this issue, it would be great if somebody could update DOCS and change examples. Without reading this ticket I would be lost.

**Comment by oohnoitz** [comment]
@ergnuor could you submit another PR to document these new changes in the README?

**Comment by ergnuor** [comment]
Yes, sure :)
