### ISSUE TITLE
unsupported filter type '(filter-type-6)' on int column 

### ISSUE THREAD

**Issue by tomcontr** [FoolCode/SphinxQL-Query-Builder#151]
Hi,

Im getting that when doing this:

    ->where('id', 'IN', $pr_ids)
pr_ids is an array that contains INTs

If I do this:

    $a = "123123,14434343,2342342,2342342";
    $pr_ids = explode(",",$a);
I get the error, but if do:

    $pr_ids = array(123123,14434343,2342342,2342342);
It works fine.

My problems is that the array comes from other script, so I cant do the second option.

**Comment by oohnoitz** [comment]
It's because you are passing in an array of strings. You will need to do some post-processing to your `explode` to cast them to `int`.

```
array_map('intval', explode(',', $stringofints));
```
