### ISSUE TITLE
Set OPTION ERROR

### ISSUE THREAD

**Issue by toanld** [FoolCode/SphinxQL-Query-Builder#160]
->option("ranker","expr('sum(exact_hit+10+lcs)*1000 +bm25')");
result error 
SQLSTATE[42000]: Syntax error or access violation: 1064 unknown ranker 'expr(\'sum(exact_hit+10+lcs*(1*exact_order))*1000 +bm25\')' [SELECT * FROM test LIMIT 0,1 OPTION ranker = 'expr(\'sum(exact_hit+10+lcs)*1000 +bm25\')']

**Comment by oohnoitz** [comment]
Going to close this unless it's still an issue. However, I believe it expects you to use `Sphinx::expr()` to bypass the quotes placed around the value (which happens automatically, except when you use the mentioned helper). So it would be something along the lines of:

```php
$rank = "expr('sum(exact_hit+10+lcs)1000 +bm25')";

$->option('ranker', SphinxQL::expr($rank));
```
