### ISSUE TITLE
Class 'Foolz\SphinxQL\Connection' not found

### ISSUE THREAD

**Issue by someApprentice** [FoolCode/SphinxQL-Query-Builder#162]
```
<?php
use Foolz\SphinxQL\SphinxQL;
use Foolz\SphinxQL\Connection;

// create a SphinxQL Connection object to use with SphinxQL
$conn = new Connection();
$conn->setParams(...);
```

fix: `use Foolz\SphinxQL\Drivers\Pdo\Connection`

**Comment by puggan** [comment]
Readme should be updated to use a existing class like `Foolz\SphinxQL\Drivers\Mysqli\Connection`

Changelog should add a note that Foolz\SphinxQL\Connection have bean droped.

**Comment by oohnoitz** [comment]
Ref 57cffab78548824015f66451bac542ec1c1d73e8. Won't publish a new release though since there aren't any changes that warrant it yet.

**Comment by puggan** [comment]
agree, github shows the readme of the master anyway, so a release is not needed at all.
