### ISSUE TITLE
Insert new index report error

### ISSUE THREAD

**Issue by caohuashan** [FoolCode/SphinxQL-Query-Builder#174]
```
$conn = new Connection();
$conn->setParams(array('host' => '127.0.0.1', 'port' => 9306));
$SphinxQL = new SphinxQL($conn);
$index = 'users';
$insert = $SphinxQL->insert()->into($index);
$data = array(
     'userId'=>100,
'name'=>'zhangsan'
);
$red = $insert->set($data)->execute();

```
It repoort error like blow:
 Uncaught Foolz\SphinxQL\Exception\DatabaseException: [1064] index 'users' does not support INSERT (enabled=1) [ INSERT INTO users

How should I resolve the problem?

**Comment by adriannuta** [comment]
INSERT can be performed only on Real-Time index type. This is not an issue of the library, check the search engine documentation.

**Comment by oohnoitz** [comment]
I'm closing this as it isn't a bug. As mentioned above, `INSERT` can only be done on real-time indices. Correct me if I'm wrong, but I believe it is the same for `DELETE` and `UPDATE` as well.
