### ISSUE TITLE
MATCH conditions are not compiled for DELETE queries

### ISSUE THREAD

**Issue by glukkkk** [FoolCode/SphinxQL-Query-Builder#176]
MATCH conditions are not compiled for DELETE queries

`$res = $query->delete()->from('rt')->match('field', 'value');`

`// this will return DELETE FROM rt; (MATCH condition is lost)`
`echo $res->compile()->getCompiled();`

**Comment by oohnoitz** [comment]
Yeah, I don't think we considered `MATCH` when we wrote this library and supported `WHERE` as the bare minimum. We didn't use the real-time indices much at the time. If you are able to get a PR up, I think the addition would be welcomed.

**Comment by glukkkk** [comment]
https://github.com/FoolCode/SphinxQL-Query-Builder/pull/179

**Comment by oohnoitz** [comment]
I merged it in. It seems like it's been a while since the last release so I'll make one in a few.

**Comment by oohnoitz** [comment]
It's been published.

**Comment by glukkkk** [comment]
Thanks!
