### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by kvkgroup** [FoolCode/SphinxQL-Query-Builder#193]
syntax error, unexpected token "match" in vendor/foolz/sphinxql-query-builder/src/SphinxQL.php:473

**Comment by premax** [comment]
Any ideas how to fix this?

**Comment by alpha0010** [comment]
https://www.php.net/manual/en/migration80.incompatible.php
> `match` is now a reserved keyword.

The class `Foolz\SphinxQL\Match` needs to be renamed.

**Comment by ben221199** [comment]
See: https://github.com/FoolCode/SphinxQL-Query-Builder/pull/197

**Comment by ben221199** [comment]
**UPDATE:**
See: https://github.com/FoolCode/SphinxQL-Query-Builder/pull/198

**Comment by Gemorroj** [comment]
@oohnoitz upd the packagist plz

**Comment by oohnoitz** [comment]
3.0.0 should be out now.
