### ISSUE TITLE
Iterating search results?

### ISSUE THREAD

**Issue by t1gor** [FoolCode/SphinxQL-Query-Builder#39]
Hi, guys.

I just actually have a question - is there a way to iterate the SphinxQL `execute()` results in a way you could do with MySQL PDO statement? The idea is to use a common ResultSet interface for MySQL and SphinxQL results in our app.

Thanks,
Igor

**Comment by oohnoitz** [comment]
Since `execute()` returns the results in an array, you should be able to use the [`ArrayIterator`](https://php.net/manual/en/class.arrayiterator.php) class and iterate the results with it. Another option would be to write a `ResultSetIterator` of some sort, mirror the MySQL PDO methods, and return it in the `Connection` class when executing the query, but that would most likely break existing code.

In your case, it may be better to create your own `Connection` class that implements `ConnectionInterface` and have it to use MySQL PDO instead. Afterwards, you would just use and pass your `Connection` class into `SphinxQL::create($conn)`.

**Comment by t1gor** [comment]
@oohnoitz, thanks, that's precisely what I did (with ArrayIterator), but it is not as efficient as it might be, as I think as I just init it with the results array.

The idea was to bring the SpinxSearch results compatible with PDO, not the PDO with SphinxSearch. I'll try to submit a pull request with the results of my exercises :) Please do not close the issue.

**Comment by oohnoitz** [comment]
@t1gor, [`Elastica\ResultSet`](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/ResultSet.php) might serve as a good example for you to use.

**Comment by t1gor** [comment]
@oohnoitz, thanks. That's a good one. I will share my results when done.

**Comment by t1gor** [comment]
Seems like it is already merged ...
https://github.com/versh23/SphinxQL-Query-Builder/commit/7e2a0d9ca2426630ce13462a59404695590b96be

right?

**Comment by versh23** [comment]
@t1gor  yes

**Comment by oohnoitz** [comment]
@t1gor there is still a need for a `ResultSet` interface and class though.

**Comment by woxxy** [comment]
I'm working on this in the `resultset` branch, but it will take some time to merge in master since the API must be agreed on.

https://github.com/FoolCode/SphinxQL-Query-Builder/tree/resultset/src/Drivers

**Comment by t1gor** [comment]
:+1: very cool. Let me see if I can help ...

**Comment by woxxy** [comment]
Right now the `resultset` branch has a fully working Mysqli driver with `ResultSet` and `MultiResultSet` implemented.

The PDO driver needs to be updated to work with its own ResultSet and MultiResultSet.
* Update the `->query()` and `->multiQuery()` methods to return `Pdo\ResultSet` and `Pdo\MultiResultSet`.
* Update `\Foolz\SphinxQL\Drivers\Pdo\(Multi)ResultSet`, right now it's just a copy of Mysqli's one. It should be mostly about renaming the methods called.

**Comment by woxxy** [comment]
As a note, you shouldn't use the PDO driver as it loses most of the optimization I could apply via Mysqli. The cursor can't be manipulated, not even reset, which means the only way to comfortably use PDO is by storing the entire result in the PHP memory, which is just like before `ResultSet`.

**Comment by t1gor** [comment]
@woxxy, actually - there is one "pro" for PDO - you can fetch items one by one by implementing `PDOResult::fetch()`.

```php
class ResultSet implements \Iterator
{
    public function __construct($stmt)
    {
        $this->_stmt = $stmt;
    }
   ...

    public function current ()
    {
        return $this->_stmt->fetch(\PDO::FETCH_OBJ);
    }
}
```

Yes, it can not be reset, but as long as MySql acts the same way in our application, we can be sure that using search and database returns compatible results.

**Comment by woxxy** [comment]
@t1gor Mysqli can do the same

**Comment by t1gor** [comment]
@woxxy good point :)

**Comment by woxxy** [comment]
The only thing to review before merging to master is the public API of ResultSetInterface. Will discuss with @oohnoitz about it soon.

**Comment by oohnoitz** [comment]
I'll close this issue now since the `resultset` branch has been pushed to `master` some time ago.
