### ISSUE TITLE
connect with user, pass, dbname

### ISSUE THREAD

**Issue by jaakkytt** [FoolCode/SphinxQL-Query-Builder#41]
Currently `Connection::connect` sets null-s to user, pass, dbname params on `mysqli::real_connect` (https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/Connection.php#L176) which makes an unnecessary restriction to what can be connected to. Suggest making those parameters available as optional while defaulting to null.

**Comment by oohnoitz** [comment]
Sphinx does not require nor use those parameters to establish a connection.
http://sphinxsearch.com/docs/current.html#conf-listen
