### ISSUE TITLE
cyrillic words in match()

### ISSUE THREAD

**Issue by versh23** [FoolCode/SphinxQL-Query-Builder#42]
hello. I can`t use cyrillic symbols in query, because  mysqli connection not in UTF8 encoding;

i created also question here http://stackoverflow.com/questions/28178379/mysqli-cant-set-encoding

**Comment by woxxy** [comment]
Yeah, we already saw the question on stackoverflow and are investigating. We supposed it comes down to PHP or MySQL client configuration.

**Comment by oohnoitz** [comment]
@versh23 Could you run the following code?

```php
$conn = mysqli_init();
$conn->real_connect('127.0.0.1', null, null, null, 9306, null);
$conn->set_charset('utf8');
var_dump($conn->error);
```

**Comment by versh23** [comment]
@oohnoitz , its return empty string.
i use ubuntu 14.04 with latest php version 5.5.9;

in mysql console match() work fine. Also i tried use a doctrine dbal connection with pdo_mysql and it work fine too.
Its a problem with mysqli configuration? but i can not find anything cofiguration for default encoding

**Comment by oohnoitz** [comment]
Since that code is returning an empty string, it does appear that the MySQLi connection has no problem loading/setting the character set to `UTF8` and that the `$conn->set_charset('utf8');` method executed successfully. I really don't know what would be causing your issue.

**Comment by versh23** [comment]
ok. I see in master branch a Connection Interface. Can i create MysqlConnection implementing interface and make PR ?

**Comment by oohnoitz** [comment]
Yes, feel free to do so.

**Comment by versh23** [comment]
@44
