### ISSUE TITLE
Add Custom Field using Formula

### ISSUE THREAD

**Issue by hey-mx** [FoolCode/SphinxQL-Query-Builder#49]
I have the problem in add new Field based on some formula like:

```
IF (title = 'something', 1, 0) As myCustomField
```

Select tries to build this field adding quotes (`) and the formula never works.

Is possible, or do you are planning define custom fields in the select method?

**Comment by oohnoitz** [comment]
@hey-mx you should be able to use `SphinxQL::expr('IF (title = "something", 1, 0) As myCustomField')`.
