### ISSUE TITLE
Select COUNT(*)

### ISSUE THREAD

**Issue by EvanLoik** [FoolCode/SphinxQL-Query-Builder#50]
Hi.
Tell me please, how can i execute this query:
```php
$SphinxQL->select('COUNT(*)')
->from('index_user')
```
As I understand, "select" variable will be wrapped in quotes before compile.

**Comment by woxxy** [comment]
Try:

    $SphinxQL->select(SphinxQL::expr('COUNT(*)'))
    ->from('index_user')

Wrapping a string into an Expression bypasses escaping: https://github.com/FoolCode/SphinxQL-Query-Builder#bypass-query-escaping

**Comment by EvanLoik** [comment]
Oh.
Excuse me :) I missed it.
