### ISSUE TITLE
select()

### ISSUE THREAD

**Issue by EvanLoik** [FoolCode/SphinxQL-Query-Builder#51]
I have another question.
Here is an example:
```php
$firstQuery = (new SphinxQL($connection))->select(['id', 'name'])
->from('index_user');

$secondQuery = clone $firstQuery;
$count = $secondQuery->select(SphinxQL::expr('COUNT(*)'))->execute();
$items = $firstQuery->execute();
```
But this code will not work, because we have this line in select method:
```php
$this->reset();
```
It is not very nice. Do you think it's necessary?
It would be great to be able to change select clause.

**Comment by alpha0010** [comment]
Since `select()` defines the type of operation being performed, the reset probably should remain.  However, I think it makes sense to add a `setSelect()` method that only changes the selected fields.
