### ISSUE TITLE
Sorting by JSON attribute

### ISSUE THREAD

**Issue by mrnull** [FoolCode/SphinxQL-Query-Builder#52]
I have following rt_attr_json nutrients with value 

     {"1":259,"3":11,"4":21,"5":5.6}

(I understand, that it's ugly).

I need to sort with something like 

    ->orderBy('nutrients.1', 'DESC')

Whan I'm tring to do so it is an error

      I have an error Uncaught exception 'Foolz\SphinxQL\DatabaseException' with message '[1064] sphinxql: syntax error, unexpected '.', expecting $end near '.`1` DESC LIMIT 0, 200' [ SELECT * FROM `food` WHERE MATCH('(@name яблочный)') ORDER BY `nutrients`.`1` DESC LIMIT 0, 200]'

**Comment by oohnoitz** [comment]
Based on some examples in the Sphinx docs, you will need to bypass the automatic escaping applied in the `orderBy()` method so that the JSON key dot notation is correct.

```php
->orderBy(SphinxQL::expr('nutrients.1'), 'DESC')
```
