### ISSUE TITLE
Travis Sphinx repo location

### ISSUE THREAD

**Issue by alpha0010** [FoolCode/SphinxQL-Query-Builder#57]
Sphinx has moved to [github](/sphinxsearch/sphinx). Build scripts need to be updated.
Also, compiling sphinx on each commit/pull takes a long time. Would you consider pulling binaries from their [ppa](https://launchpad.net/~builds/+archive/ubuntu/sphinxsearch-rel22)?

**Comment by oohnoitz** [comment]
Yup. These suggestions have been pushed in 258725ee798825eeb847c77332f398115e0a0e00. I'll close this issue once the build passes.
