### ISSUE TITLE
Unused WHERE functions

### ISSUE THREAD

**Issue by alpha0010** [FoolCode/SphinxQL-Query-Builder#66]
Sphinx does not support parenthesizing nor OR options in WHERE clauses, making `orWhere()`, `whereOpen()`, `orWhereOpen()`, and `whereClose()` unusable.  Is there any reason for keeping them around?
Also, if parentheses are needed in the future, laravel has a [nicer way](http://laravel.com/docs/5.1/queries#advanced-where-clauses).

**Comment by oohnoitz** [comment]
I think those were there in case Sphinx ever supported them, but we could probably remove them. Also, I agree, if we do need them, it should be implemented the same way as Laravel's query builder to avoid any possible user-related errors.

**Comment by alpha0010** [comment]
Okay.
There are also the helpers `showSessionVariables()` and `showGlobalVariables()` which [according to docs](http://sphinxsearch.com/docs/current.html#sphinxql-show-variables) are there simply for compatibility (and do nothing different than `showVariables()`).
