### ISSUE TITLE
join with mysql table

### ISSUE THREAD

**Issue by 2ge** [FoolCode/SphinxQL-Query-Builder#70]
Hi,

I am thinking to add your lib to my project and start to using it, but I am not sure, if it can handle for example something like this:

```SQL
SELECT * 
FROM sph_search a
LEFT JOIN my_table b on a.id = b.IDItem
WHERE query='test;mode=all;index=*' 
LIMIT 10;
````

Thanks

**Comment by alpha0010** [comment]
This library is an abstraction over SphinxQL, which according to [the docs](http://sphinxsearch.com/docs/current.html#sphinxql-reference), does not have a `JOIN` statement.

**Comment by 2ge** [comment]
Thank you.
