### ISSUE TITLE
OrderBy on Expression

### ISSUE THREAD

**Issue by 2ge** [FoolCode/SphinxQL-Query-Builder#71]
Hi,

is there some way to use OrderBy on Expression ? For example this works in SphinxQL:
```
SELECT *, WEIGHT()*10+docboost AS skey FROM example ORDER BY skey
```

I was not able to write using SQB, not able to alias the field:
```
$ql->select('*', 'WEIGHT()*10+docboost AS skey')->from('example')->orderBy('skey');
```

Example taken from http://sphinxsearch.com/docs/current/sphinxql-select.html

Thanks

**Comment by alpha0010** [comment]
Wrapping your computation with `SphinxQL::expr($string)` should work (bypasses query escaping).

```php
$ql->select('*', SphinxQL::expr('WEIGHT()*10+docboost AS skey'))
    ->from('example')
    ->orderBy('skey');
```

**Comment by 2ge** [comment]
works great, thank you!
