### ISSUE TITLE
SphinxQL Query Builder FACET example

### ISSUE THREAD

**Issue by 2ge** [FoolCode/SphinxQL-Query-Builder#72]
Hi,

would you mind sharing simple Match(...) with FACET example code ?

Thanks.

**Comment by oohnoitz** [comment]
@2ge You can find how to use FACET in the [tests](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/tests/SphinxQL/SphinxQLTest.php#L903-L948). I believe that the `match()` method is already documented.

**Comment by 2ge** [comment]
Sure, didn't look there. Thank you, works like charm!
