### ISSUE TITLE
halfEscapeMatch function

### ISSUE THREAD

**Issue by arthfael-breanainn** [FoolCode/SphinxQL-Query-Builder#75]
Hi all,

       I've an issue with halfEscapeMatch function. When I try this request : 
SELECT * FROM rt_index WHERE MATCH('(@(title,text) \\(\"ford\"\\) -\\(\"mustang\" | \"shelby\"\\))');

it returns all down results containing "ford" including "mustang" and "shelby".
However, if I exclude parenthesis into $escape_half_chars array, my request becomes : 
SELECT * FROM rt_index WHERE MATCH('(@(title,text) (\"ford\") -(\"mustang\" | \"shelby\"))');

Now it returns all down results containing "ford" without "mustang" and "shelby".
I think $escape_half_chars array should be : 
$escape_half_chars = array(
'\\' => '\\\\',
'!' => '\!',
'@' => '\@',
'~' => '\~',
'&' => '\&',
'/' => '\/',
'^' => '\^',
'$' => '\$',
'=' => '\=',
'<' => '\<',
);

What do you think about this ?

**Comment by oohnoitz** [comment]
@arthfael-breanainn I'm not sure and feel that those characters might vary on a per-project basis which is why we implemented methods to allow developers to override those defaults. You can use `setFullEscapeChars($array)` and `setHalfEscapeChars($array)`.

**Comment by arthfael-breanainn** [comment]
@oohnoitz thx, now my application work very well.
