### ISSUE TITLE
Handling MVA in Sphinx with the QueryBuilder

### ISSUE THREAD

**Issue by SvetlinStaev** [FoolCode/SphinxQL-Query-Builder#77]
Hi,

I am having an issue with adding multi value attributes using the QueryBuilder. When I added the values it gives me:

[1064] row 1, column 8: non-MVA value specified for a MVA column [ INSERT INTO `auctions_rt` (`id`, `title`, `description`, `attribute_5`, `attribute_4`, `attribute_3`, `attribute_2`, `attribute_1`) VALUES (83, 'test', 'test', 'test', 0, 'test 1', 'test', '')]

From what I read in the documentation the multi value attributes should be enclosed with parenthesis to work. Is there a way to achieve that with the querybuilder or it is not yet supported?

The SQL statement should look like:
INSERT INTO `auctions_rt` (`id`, `title`, `description`, `attribute_5`, `attribute_4`, `attribute_3`, `attribute_2`, `attribute_1`) VALUES (83, 'test', 'test', ('test'), (0), ('test 1'), ('test'), (''));

**Comment by oohnoitz** [comment]
Can you provide the code you used to generate the `INSERT` statement?

**Comment by SvetlinStaev** [comment]
I am using a Doctrine entity and a model transformer to get only the fields which are needed for the index. It is an Auction entity which indexes title and description and based on a given category allows the user to enter a dozen specific attributes - let's say for a Car category it will be model, make, year etc.

After the entity is transformed to an array I get to this:

```php
        $index = 'auction_rt';
        $document = array('id' => 1, 'title' => 'test', 'description' => 'test', 'attribute_1' => 'test', 'attribute_2' => 'test', 'attribute_3' => 'test', 'attribute_4' => 'test', 'attribute_5' => 'test');
        $query = SphinxQL::create($this->getConnection())->insert()->into('`'.$index.'`');

        foreach ($document as &$value) {
            if (null === $value) {
                $value = '';
            }
        }
        $query->columns(array_keys($document))->values($document);
        $query->execute();
```

from what I see in the stack trace it goes through:

```php
return $this->last_result = $this->getConnection()->query($this->compile()->getCompiled());
```
in in vendor/foolz/sphinxql-query-builder/src/SphinxQL.php at line 275

and then fails with:

```php
throw new DatabaseException...
```

I think the problem is more in respect to the values being MVA rather then a standard ones. I am not sure whether the library has support for that. Just as a reference here is my Sphinx configuration for that index:

```
index auctions_rt
{
	type			= rt
	path			= /usr/local/var/data/sphinx/auctions_rt
	morphology	= stem_en

	rt_mem_limit	= 128M

	rt_field		= title
	rt_field		= sub_title
	rt_field		= description
	rt_field		= additional_information

    rt_attr_multi   = attribute_1
    rt_attr_multi   = attribute_2
    rt_attr_multi   = attribute_3
    rt_attr_multi   = attribute_4
    rt_attr_multi   = attribute_5
    rt_attr_multi   = attribute_6
    rt_attr_multi   = attribute_7
    rt_attr_multi   = attribute_8
    rt_attr_multi   = attribute_9
    rt_attr_multi   = attribute_10
}
```

**Comment by oohnoitz** [comment]
Can you use the following for the document as the argument passed into the `values()` method?

```php
$document = [
  'id' => 1,
  'title' => 'test',
  'description' => 'test',
  'attribute_1' => ['mva test'],
  'attribute_2' => ['mva test'],
  'attribute_3' => ['mva test'],
  'attribute_4' => ['mva test'],
  'attribute_5' => ['mva test']
];
```

The library doesn't have any knowledge of how your indexes are structured. It simply assumes that none of the values are a multi-valued attribute. In order to have the query builder hint that a field is a MVA, you would need to make sure that the values are wrapped within an array. This would then go through our internal [`quote` method](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/Drivers/ConnectionBase.php#L155-L158) which translates many of the values to ones supported by Sphinx.

**Comment by oohnoitz** [comment]
@SvetlinStaev were you able to resolve your problem?

**Comment by SvetlinStaev** [comment]
Hi,

Yeah, works like a charm! Thanks for the help.
