### ISSUE TITLE
JSON fields support

### ISSUE THREAD

**Issue by yschapov** [FoolCode/SphinxQL-Query-Builder#80]
This is very real. Users post problems they experience with JSON fields, i.e.:

```
$conn = new Connection();
  $query = SphinxQL::create($conn)->select('product_id')->from('parameter_index');
  if (!empty($data['minCoast']) and !empty($data['maxCoast'] and ($data['minCoast'] <  $data['maxCoast']) )) {
  $query -> where('attr.coast', 'BETWEEN', [$data['minCoast'],$data['maxCoast']]);
}

if (!empty($data['catalog'])) {
  $query -> where('attr.catalog_id', '=', $data['catalog']);
}
$total = $query->execute();
```
It causes an error:

``syntax error, unexpected $undefined, expecting IDENT (or 97 other tokens) near '`attr[coast]` BETWEEN '1000' AND '7000' AND `attr[catalog_id]` = '2'' [ SELECT `product_id` FROM `parameter_index` WHERE `attr[coast]` BETWEEN '1000' AND '7000' AND `attr[catalog_id]` = '2']```

The matter is ```'attr.catalog_id'``` and ```'attr.coast'``` are JSON fields. A working request would be (note that backticks were partially removed):

```attr["coast"] BETWEEN '1000' AND '7000' AND attr["catalog_id"] = '2'' [ SELECT `product_id` FROM `parameter_index` WHERE attr["coast"] BETWEEN '1000' AND '7000' AND attr["catalog_id"] = '2'```

This is because Sphinx currently cannot parse JSON fields that are surrounded by backticks. MySQL wouldn't parse that syntax either, e.g. `test.table` surrounded with backticks wil end up with a syntax error.

I suggest removing backticks as a whole (Sphinx fields can't contain spaces anyway) or at least remove backticks from JSON fields.

Also I noticed that ```attr.catalog_id``` becomes ```attr[catalog_id]``` which is also wrong (not sure if it's Query builder or user's request though). The proper syntax would be either ```attr.catalog_id``` or ```attr["catalog_id"]```.

**Comment by woxxy** [comment]
> Also I noticed that attr.catalog_id becomes attr[catalog_id] which is also wrong (not sure if it's Query builder or user's request though). 

It looks like your user is using that in the query.

The [quoteIdentifier function](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/Drivers/ConnectionBase.php#L94) would give as output:

    `attr`.`catalog_id`

which I wouldn't know whether it's valid SphinxQL without testing myself.

A temporary solution would be passing that field via `SphinxQL::expr('attr.catalg_id')`, which will disable the backticks.

We're considering removing backticks now (should be all in that function linked).

**Comment by yschapov** [comment]
Unfortunately ```"`attr`.`catalog_id`"```  is not (yet) supported either. Subkeys with spaces currently can be adressed via json["field with spaces"].

**Comment by woxxy** [comment]
Alright, then we're pretty sure we'll solve this by removing the backticks.

**Comment by yschapov** [comment]
Cool! I think the issue may be closed.
