### ISSUE TITLE
compileMatch: Problem with column names matching native PHP functions

### ISSUE THREAD

**Issue by qwerdy** [FoolCode/SphinxQL-Query-Builder#82]
If you incidentally have a column name matching a native PHP function, the column name ($pre) in the compileMatch() method will be empty for the match.

E.g I have a index with a column named "header" in it, this causes a match on the "is_callable" check.

**Comment by woxxy** [comment]
I guess this slipped in a pull request. I will check throughly what the code is supposed to do when I get home.

Should've likely been `instanceof Closure`. If you're in a hurry, try replacing:
- `is_callable($match['column'])` with `$match['column'] instanceof Closure`
- `is_callable($this->from)` with `$this->from instanceof Closure`
