### ISSUE TITLE
Is it possible to do wildcard searches?

### ISSUE THREAD

**Issue by dannykopping** [FoolCode/SphinxQL-Query-Builder#84]
I've set the following options in my index, but it still doesn't seem to work:

```
enable_star = 1
dict = keywords
```

**Comment by oohnoitz** [comment]
Yes, you would need to use the `match()` methods to formulate your wildcard search queries. Also, `enable_star` should have been deprecated as of `2.2.x`.

**Comment by dannykopping** [comment]
I am using the `match()` method, but I'm doing it across all fields:

```php
$statement  = SphinxQL::create($connection)
            ->select(['sku', 'price', 'normal_price', 'rating'])
            ->from(SPHINX_PRODUCTS_INDEX)
            ->match('*', $query)
            ->groupBy('id_catalog_config')
            ->orderBy('WEIGHT()', 'DESC')
            ->orderBy('is_new', 'DESC')
            ->limit($limit * $iteration, $limit)
            ->option('max_matches', self::MAX_ITERATIONS * $limit);
```

**Comment by lmuzinic** [comment]
Are you using min_prefix_len/min_infix_length in config as well?

**Comment by dannykopping** [comment]
No - I'm using lemmatization, and that only works with morphology IIRC?

**Comment by lmuzinic** [comment]
Lemmatization will only create "base tokens" such as "creates, created, create" => create (depending on dictionary used). This will not help you if you want to search for "cr*"

**Comment by dannykopping** [comment]
Sure, and i need the lemmatization for other use-cases, but the wildcard search doesn't seem to work. Are the two mutually exclusive - is that what you're saying?

**Comment by lmuzinic** [comment]
No, they should not be and there is no need to be. Lemmatization approaches from language/dictionary perspective, while prefix simply takes each word and create all possible variations up to min_prefix_len. For example, min_prefix_len = 2 will create 4 items in index he, hel, hell, hello from word hello

**Comment by dannykopping** [comment]
Cool, that's what I thought - thanks @lmuzinic. So i'm sure i tried `min_prefix_len` - is there any option i need to set in SphinxQL to make this wildcard search possible? Or some way I can debug why I'm getting no results?

**Comment by oohnoitz** [comment]
You shouldn't need to fiddle with anything besides `min_prefix_len` and `min_infix_len`. For debugging, I would suggest using any MySQL client and calling `->compile()->getCompiled()` on the query builder to get a SphinxQL statement you can run in the client.

**Comment by dannykopping** [comment]
Amazing, got it working! Thanks so much guys :+1:

**Comment by lmuzinic** [comment]
Great! Care to share what was the catch?
