### ISSUE TITLE
Call set() multiple times

### ISSUE THREAD

**Issue by razvanphp** [FoolCode/SphinxQL-Query-Builder#86]
Hello

For efficiency and clean code on our side, we would like to be able to make a multi insert by calling set multiple times, because that's how our data is structured, as models.

Currently this is not working, since set is assuming it's called only once. It should be done a little bit more intelligent, for example checking if the column name already exists into the `$this->columns` array and not hard coding `$this->values[0][]` in `value()` method.

I can prepare a PR for this if you are also interested.

Thank you!

**Comment by oohnoitz** [comment]
Feel free to submit a PR for us to take a look at.
