### ISSUE TITLE
Unable to select snippet or use Helper to get snippet

### ISSUE THREAD

**Issue by abodnar** [FoolCode/SphinxQL-Query-Builder#90]
I'm trying to use your library to retrieve a snippet for some text based off of some keywords, but when it tries to do it for certain text, it just fails and I don't get any sort of error.

```php
$conn = new Connection();  
$conn->setParams(['host' => env('SPHINX_HOST', ''), 'port' => env('SPHINX_PORT', '')]);

$keywords = "word1 word2 word3";
foreach ($docs as $document) {
       $query = SphinxQL::create($conn)->select("SNIPPET(" . $conn->escape($document->text) . ", " . $conn->escape($keywords) . ", 'limit=1000')")
->from('index')
->where('document', '=', 1);
        $result = $query->execute();
}
```

I've also tried it using the helper method to get a snippet.

```php
$query = Helper::create($conn)->callSnippets($document->abstract, 'PatentIndexes', $conceptText, ['limit' => 1000]);
```

But I get this error: The distributed index for snippets must have exactly one local agent

Not all of the text I try with hits an error when I do the SELECT SNIPPET, but an example one is this:

> 
Selected beef subprimals were obtained from fabrication lines of three foodservice purveyors to assist in the development of a software support program for the beef foodservice industry. Subprimals were fabricated into bone-in or boneless foodservice ready-to-cook portion-sized cuts and associated components by professional meat cutters. Each subprimal was cut to generate mean foodservice cutting yields and labor requirements, which were calculated from observed weights (kilograms) and processing times (seconds). Once fabrication was completed, data were analyzed to determine means and standard errors of percentage yields and processing times for each subprimal. Subprimals cut to only one end point were evaluated for mean foodservice yields and processing times, but no comparisons were made within subprimal. However, those traditionally cut into various end points were additionally compared by cutting style. Subprimals cut by a single cutting style included rib, roast-ready; ribeye roll, lip-on, bone-in; brisket, deckle-off, boneless; top (inside) round; and bottom sirloin butt, flap, boneless. Subprimals cut into multiple end points or styles included ribeye, lip-on; top sirloin, cap; tenderloin butt, defatted; shortloin, short-cut; strip loin, boneless; top sirloin butt, boneless; and tenderloin, full, side muscle on, defatted. Mean yields of portion cuts, and mean fabrication times required to manufacture these cuts differed (P < 0.05) by cutting specification of the final product. In general, as the target portion size of fabricated steaks decreased, the mean number of steaks derived from any given subprimal cut increased, causing total foodservice yield to decrease and total processing time to increase. Therefore, an inverse relationship tended to exist between processing times and foodservice yields. With a method of accurately evaluating various beef purchase options, such as traditional commodity subprimals, closely trimmed subprimals, and pre-cut portion steaks in terms of yield and labor cost, foodservice operators will be better equipped to decide what option is more viable for their operation.
>

I know the query works cause I connected directly to the Sphinx index with MySQL and ran the query and it worked fine.

Any ideas or suggestions would be appreciated.

Thanks.

**Comment by oohnoitz** [comment]
@abodnar Based on the error you pasted, it looks like a configuration error since you appear to have a distributed index setup. I don't have much experience using the snippet feature, but using the example you provided works perfectly fine for me for in a local index setup.

**Comment by abodnar** [comment]
Looks like it was due to the distributed index was causing problems. Worked fine when I switched to one of the actual indexes. I also got my query to work when I switched to the actual index as well and modified my query.

I see that the callSnippets actually does a CALL SNIPPET query. Do you if this is slower than doing the SELECT SNIPPET query?

Thanks.

**Comment by oohnoitz** [comment]
Based on the [documentation](http://sphinxsearch.com/docs/latest/sphinxql-select.html), there might be some reasons why you would want to use the `SNIPPET()` function. There shouldn't be any performance issues with using either normally though. Anyway, I'll mark this as closed.
