### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by abreksa4** [FoolCode/SphinxQL-Query-Builder#91]
Would be great to have json support as per http://sphinxsearch.com/blog/2013/08/08/full-json-support-in-trunk/ and http://sphinxsearch.com/bugs/view.php?id=1690

**Comment by oohnoitz** [comment]
@abreksa4 I'm not sure what you have in mind, but it should already be possible to write and execute queries with JSON attributes. This can be done using `Sphinx::expr($string)` and `where($column, $operator, $value)`.
