### ISSUE TITLE
GEODIST function support

### ISSUE THREAD

**Issue by SvetlinStaev** [FoolCode/SphinxQL-Query-Builder#93]
Hi,

I am not really sure if it is an issue with the current setup but I can't really get the ```GEODIST``` function working correctly. Is there support for that in the library or it needs to be implemented in a similar way to what the ```Facet``` class does?

An example of what I am trying to achieve:

```sql
SELECT *, GEODIST(0.659298124, -2.136602399, latitude, longitude) as distance FROM locations WHERE distance < 10000;
```

**Comment by oohnoitz** [comment]
@SvetlinStaev this should be possible with the following:
```php
select('*', Sphinx::expr('GEODIST(..., ..., longitude, latitude) as distance'))
```

**Comment by SvetlinStaev** [comment]
Works perfectly, thanks!
