### ISSUE TITLE
Can't do OR in match

### ISSUE THREAD

**Issue by Alabme** [FoolCode/SphinxQL-Query-Builder#94]
Hi,

I think it is impossible right now achieve in Your library something like this:

```sql
 SELECT * FROM `Index` WHERE MATCH('((@country DE @locality Berlin) | (@country DE @locality empty @postal_code empty))');
```

I'm talking about `|` operator between fields. I need to find documents where `country = DE and locality = Berlin` OR `country = DE and locality = empty and postal_code = empty`

Or maybe I'm wrong?

Best regards,
Tomek Będkowski

**Comment by oohnoitz** [comment]
It's possible. You can take a look at our [MATCH tests](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/tests/SphinxQL/MatchTest.php) for some examples.

**Comment by Alabme** [comment]
@oohnoitz thanks for answer! 
It seems it is definitely possible, sorry for the trouble.
