### ISSUE TITLE
Boolean quoting behaviour

### ISSUE THREAD

**Issue by alpha0010** [FoolCode/SphinxQL-Query-Builder#98]
I noticed that [in quoting](https://github.com/FoolCode/SphinxQL-Query-Builder/blob/master/src/Drivers/ConnectionBase.php#L134), `true` => `"'1'"` and `false` => `"'0'"`. Is there a reason for this? The sphinx bool attribute requires the integer `1` or `0` to be used.

**Comment by oohnoitz** [comment]
@alpha0010 I can't seem to recall why we have it doing that. It should be returning a `1` and `0`, respectively, when passing `true` and `false` there.
